### ISSUE TITLE
comments on latest draft

### ISSUE THREAD

**Issue by beanumber** [ambertin/thesis#6]
- pg. 2: 
    - you use "incredibly" three times on this page. I would delete all three uses. 
    - "This paper" -> "This thesis"
- pg. 15:
    - "[Alt]hough this is..."
- pg. 16: 
    - It seems the paragraph starting "Acceptance of..." is a quotation? If so, perhaps set it off as a blockquote. 
- pg. 18:
    - "The most famous course..." -- how do you know that this is the most famous course? If you have no evidence, don't make the claim. 
- pg. 27:
    - "...were published in..." -- This isn't true. The `miceps` data is much more recent than 2010 and hasn't been published anywhere. 
    - "The folder contains..." -- it looks like this paragraph contains a list that isn't being formatted properly. 
    - [MIME type](https://en.wikipedia.org/wiki/Media_type) is a real thing!
- pg. 29
    - It seems like the output of `proj_render(temp_dir)` is cut off? 
- pg. 37-38:
    - You switch from `read.csv()` to `read_csv()`. Is this on purpose? 
    - In the discussion of `here::here()`, one of the advantages of this function is that it allows you to reference file paths in scripts in a manner that is independent of where the scripts are located and where they are being run. If they get moved, the file paths still resolve correctly. 
- pg. 46:
    - In the paragraph beginning "When `proj_analyze()`..." it seems like there is a list that is not being formatted properly. 
- pg. 50:
    - There is a space missing after the comma before `proj_analyze()`. 
- pg. 55:
    - There is a space missing after `project_analyze()`. 
- pg. 59:
    - "...is dependent [on] `fertile`..."
    - "...version of `library()`,[ ]`fertile` is detached..." -- insert space 
    - "...provided by `fertile` is [provided] below."
    - "Note that--" -- remove en-dash
- pg. 60:
    - "As a result of this, we believe...." -- use present tense. 
- pg. 63:
    - A space is missing between "called" and "`FERTILE_RENDER_MODE`"
- pg. 66:
    - A space is missing between `readr::read_csv()` and "arguments"
- pg. 67:
    - I don't think you need the colon at the end of the page. 
- pg 69:
    - "It is, of course, ~~though~~, important..." -- strike "though"
    - "The ~~the~~ interactive

**Comment by ambertin** [comment]
Great! Will get on this ASAP! Thank you!!

**Comment by ambertin** [comment]
All of these addressed in https://github.com/ambertin/thesis/commit/dec4f73e0f63ffd33226c8418c14a226e291eb73!

Also fixed a spot where I found a function name missing its `()`
